### ISSUE TITLE
[Bug] Openverse Search Button Has Thicker Border, Leading to Poor UX

### ISSUE THREAD

**Issue by mo-gbolahan** [creativecommons/search#254] opened 2024-10-05 17:14 UTC
## Description
 The button for the Openverse search engine has a noticeably thicker border compared to other buttons on the page. This causes it to stand out visually even when it’s not being clicked or hovered over, which sends the wrong feedback to users. Buttons should only draw attention during interaction (e.g., hover or click), not in their default state.

## Reproduction

1. Navigate to the search pagewith the Openverse search button.
2. Observe the thicker border around the button compared to other buttons on the page.
3. Notice that this thicker border is present even without interaction.

## Expectation
he search button should have a consistent border thickness that matches other buttons, ensuring a uniform look across the UI. Visual feedback (e.g., a border change) should only occur during interaction, such as hover or click.

## Screenshots
![Screenshot (27)](https://github.com/user-attachments/assets/484d295a-29a9-4766-aab3-baee3300454a)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment] 2024-10-07 14:20
This was an intentional decision to direct more traffic to OpenVerse as it includes a wide variety of sources in its results (and since what is now referred to as OpenVerse used to be the CC Search before it was transferred to Automattic several years ago.

Closing as this is expected behavior.

**Closed by possumbilities** 2024-10-07 14:20 UTC
Labels: 🟧 priority: high, 🚦 status: awaiting triage, 🛠 goal: fix, 💻 aspect: code
