### ISSUE TITLE
[Feature] the primary menu as well as button in ancilliary-menu is missing

### ISSUE THREAD

**Issue by Sophiek9h** [creativecommons/search#245] opened 2024-10-04 12:54 UTC
##Problem
Disparities in design of the header in search portal and Vocabulary 

## Description
the **primary-menu** that consists of  "about, contact, blog, support" as well a button in ancilliary-menu is missing in the search portal 

## Implementation
The nav class should be collected from vocabulary and used in the search portal 

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment] 2024-10-07 14:07
Hi and thanks for this contribution! 

This is a duplicate of an already closed issue #237. Please verify a Issue doesn't already exist before creating a new one.

Please see the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/)

Closing as duplicate.

**Closed by possumbilities** 2024-10-07 14:07 UTC
Labels: 🟩 priority: low, 🚦 status: awaiting triage, ✨ goal: improvement, 💻 aspect: code

**Comment by Sophiek9h** [comment] 2024-10-07 15:00
Oh
Thanks for the feedback
