### ISSUE TITLE
[Bug] Wrong Spelling(Typing Error)

### ISSUE THREAD

**Issue by FrancoFrancis** [creativecommons/search#79] opened 2022-10-12 17:58 UTC
This PR   #71  by me fixes this issue

## Description
buttons typed  as **btutons** instead of **buttons** in `search.js`  file line 15.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by ImaJin14** [comment] 2022-10-12 18:11
Conflicting with #75 but no big deals one will be closed!!!

**Comment by FrancoFrancis** [comment] 2022-10-12 18:13
I am so sorry I am creating an issue after opening a pr, according to the guidelines I am supposed to open one before creating a PR.

**Comment by FrancoFrancis** [comment] 2022-10-12 18:21
> Conflicting with #75 but no big deals one will be closed!!!

Thank you bro.

**Comment by possumbilities** [comment] 2022-10-12 19:56
duplicate of #75

**Closed by possumbilities** 2022-10-12 19:56 UTC
Labels: 🟩 priority: low, 🚦 status: awaiting triage, ✨ goal: improvement, 💻 aspect: code
