### ISSUE TITLE
footer issues and misspelled comment

### ISSUE THREAD

**Issue by MariamOsman11** [creativecommons/search#64] opened 2022-10-11 17:05 UTC
the footer design is not the most good looking. some social media icons should be included e.g instagram, Tiktok. Also,
some  code comments is mispelled. And, i'll like to fix those two stuff if given opportunity.

**Comment by ImaJin14** [comment] 2022-10-11 18:12
I think this issue conflicts with issue #60...

**Comment by MariamOsman11** [comment] 2022-10-11 20:12
@ImaJin14  I committed and pushed  the spelling hours ago before I come to the discussion and discovered later that it was said.

**Comment by possumbilities** [comment] 2022-10-11 20:44
Closing this since it's a duplicate of #60

**Closed by possumbilities** 2022-10-11 20:44 UTC
Labels: 🟧 priority: high, 🚦 status: awaiting triage, 🛠 goal: fix, 💻 aspect: code
