### ISSUE TITLE
[Feature]  Disable Search Button When No Term is Entered

### ISSUE THREAD

**Issue by Netacci** [creativecommons/search#252] opened 2024-10-05 11:00 UTC
## Problem

Currently, when a user presses the search button without entering a search term, an alert modal pops up. This disrupts the user experience and may feel intrusive. A more user-friendly approach would be to either provide form validation feedback or disable the search button until a search term is entered.

![search](https://github.com/user-attachments/assets/c565a714-b896-4626-84c5-a6d670cc19a5)

## Description

Pressing the search button with no term entered triggers an alert, which is not ideal for user experience. A better solution could involve disabling the search button until the user enters a valid search term.

## Alternatives

- Form Validation: Provide a visual indication with a message such as "Please enter a search term" when the button is clicked with an empty input.
- Form validation provides clear feedback but may add more interaction if users frequently forget to enter a term.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by possumbilities** [comment] 2024-10-07 18:24
I believe this is a duplicate of:

#238 

If there's information relevant that should be there, please move it into a comment on the original Issue.

**Closed by possumbilities** 2024-10-07 18:24 UTC
Labels: 🟩 priority: low, 🚦 status: awaiting triage, ✨ goal: improvement, 💻 aspect: code
