### ISSUE TITLE
[Feature] Redesign the Card and Search Component

### ISSUE THREAD

**Issue by Straw4yu** [creativecommons/search#70] opened 2022-10-12 10:04 UTC
## Problem

The current card and search component is not attractive visually and does not meet the standard of design.

## Description

This feature will make the section more attractive and open to all.

## Additional context

As a Frontend developer, the section does not meet a good standard and needs to be worked on. The goal is to make an attractive and good looking search section that will be open to all.

## Implementation

- [ x] I would be interested in implementing this feature.
![Feature  Redesign Card and Search Component](https://user-images.githubusercontent.com/102481992/195310071-4db164ec-a9b7-49f9-94d9-9259cbea7f3f.jpeg)

**Comment by Straw4yu** [comment] 2022-10-12 10:05
@possumbilities and @TimidRobot I'll like to work on this issue.

**Comment by PreciousOritsedere** [comment] 2022-10-12 11:54
@Straw4yu can we work on this together? When the issue is approved of course

**Comment by Straw4yu** [comment] 2022-10-13 08:48
@possumbilities The new card component is more visually appealing because it consists of images that portray the information displayed on the cards, giving the viewers an understanding, also the images create a nice contrast to match with the newly designed footer (in black and white) giving off a simple and contrasting use of colour.

The new card component portrays a direct meaning of the information with the use of images.

I sourced for free images off the web to implement the design.

**Comment by ImaJin14** [comment] 2022-10-13 09:09
@Straw4yu your issue has been approved hence a PR will very much be appreciated with free license documents of course:)

**Comment by PreciousOritsedere** [comment] 2022-10-13 09:17
@ImaJin14 to avoid confusion, no it haven’t been approved. It has the ‘ticket work required’ status because it needs more explanatory details before it can be considered for approval .

When it happens the ‘ready for work’ status, that’s when it can be worked on and a PR can be created.

**Comment by PreciousOritsedere** [comment] 2022-10-13 09:19
@Straw4yu if this is to be implemented, that means we’ll need to get descriptive images for each search component?

**Comment by ImaJin14** [comment] 2022-10-13 09:22
> @Straw4yu if this is to be implemented, that means we’ll need to get descriptive images for each search component?

For each search engine rather:)

**Comment by Straw4yu** [comment] 2022-10-13 09:26
@ImaJin14 Yes, for each search engine. That's why I made another clearification on the existing feature.waiting for @possumbilities for approval.

**Comment by PreciousOritsedere** [comment] 2022-10-13 09:27
I think it’s a nice idea 😊 I like it

**Comment by ImaJin14** [comment] 2022-10-13 09:29
> @ImaJin14 to avoid confusion, no it haven’t been approved. It has the ‘ticket work required’ status because it needs more explanatory details before it can be considered for approval .
> 
> When it has the ‘ready for work’ status, that’s when it can be worked on and a PR can be created.

Yeah that's y he is giving more details on how and what his issue is about 


I'm just stating that he could work on the issue locally while awaiting for the status ready for work to push his commits:)


PS he will need to provide either SVG or PNG files for the various search engines and they have you be open source...

**Comment by Straw4yu** [comment] 2022-10-13 09:39
> > @ImaJin14 to avoid confusion, no it haven’t been approved. It has the ‘ticket work required’ status because it needs more explanatory details before it can be considered for approval .
> > When it has the ‘ready for work’ status, that’s when it can be worked on and a PR can be created.
> 
> Yeah that's why he is giving more details on how and what his issue is about
> 
> I'm just stating that he could work on the issue locally while awaiting for the status ready for work to push his commits:)
> 
> PS he will need to provide either SVG or PNG files for the various search engines and they have you be open source...

@ImaJin14 Yes... each search engines will have an image file that portray the information on what the search engine does.

**Comment by Straw4yu** [comment] 2022-10-13 18:24
@possumbilities waiting for approval to get this implemented. Thank you.

**Comment by possumbilities** [comment] 2022-10-13 20:00
@Straw4yu hello, and thank you for proposing this! It's an intriguing idea. 

Something I'd like all of us to discuss here in the comments is what precise images would be selected. Do you have a series in mind, keeping in mind that they would have to be images that are within our ability to use rights-wise?

As an alternative viewpoint, what are the arguments against this approach? I agree it's visually appealing in one sense, but it also requires several images to load for a user, which could impact UX and performance.

Furthermore, mixing images with text over them presents Accessibility concerns we'd have to address with readability and contrast.

The overall argument against this approach is, while appealing, it adds complexity to the UX. Anyone have thoughts on that? 

I'm interested in what others have to say, please feel free to offer suggestions as contributions here in the conversation. ❤️

**Comment by dikehprosper** [comment] 2022-10-14 10:26
@possumbilities first of all, about the issue of image loading,
we can optimize them and make them load faster by....
using a resizable  SVG image for different browsers i.e (without a fixed width and height allowing it to stretch to whatever the container allows it).... alongside using a 'viewBox' attribute to allow the content to scale properly.

2. about the accessibility issue
...

The safest option might be avoiding using images with an irregular background altogether…

BUT THEN ALTERNATIVELY 
Adding an additional opacity layer between the image and the text is one option. If the text has a light color, a dark opacity layer can be used. Alternatively, if the text has a dark color, we can use a light opacity layer. If opacity layering for a whole image is too visually invasive, we can use an opacity gradient and position the text over the section with the most solid color to have a compliant contrast ratio. 

TEXT BORDER AND OUTER SHADOW IS ANOTHER
 As this is measured against the text body and not the background like the previous technique.

If we choose to use borders for our text, it’s important to note there are two aspects to this technique: border width and border color. When it comes to border width, the contrast ratio between the border and the font body should be at least 4.5:1. Yet, if the width is 3px or greater, the minimum contrast ratio goes down to 3.0:1.


On the contrary, if we choose to use outer shadowing, shadow properties should obviously be taken into account. These are: distance, opacity, spread and size.

Distance: the value must be 0px because contrast ratio measurement is done between adjacent colors.
Opacity: the transparency should be high enough for the background to be differentiated from the shadow color.
Spread: the percentage should be low enough for the shadow not to be blurred.
Size: the value must be set in accordance with the spread, as a 3px shadow size will not be effective as a means to achieve compliance if the spread percentage is too high.


And lastly about using image use right-wise….
They’re tons of websites like pexels.com,pixabay …that offers free stock photos and images that can be used for the project…while this is good it’s way better to use the company’s own set of images specific only to them and not random images found on random websites….Thank you

**Comment by Straw4yu** [comment] 2022-10-15 10:09
@possumbilities Some suggestions were made on this issue and we are awaiting your contribution on the suggestions made. Thank you.

**Comment by Straw4yu** [comment] 2022-10-19 19:09
@possumbilities Is there any review on the contributions made earlier as more details are added.

**Comment by possumbilities** [comment] 2024-03-04 15:59
Resolved in new site merge: https://github.com/creativecommons/search/pull/206

**Closed by possumbilities** 2024-03-04 15:59 UTC
Labels: 🟩 priority: low, 🧹 status: ticket work required, ✨ goal: improvement, 💻 aspect: code
