### ISSUE TITLE
[Bug] Improve the search input and search button UI in mobile screen

### ISSUE THREAD

**Issue by Demi-la** [creativecommons/search#253] opened 2024-10-05 12:47 UTC
## Description
The search input and search button UI on mobile screens are currently displayed side by side with separate border radii, making them look disconnected. Additionally, both the search input and search button are the same width, but the search input should be wider than the button for better usability and aesthetics

## Reproduction

1. Open the application on a mobile device or use the responsive mode in a browser's developer tools.
2. Observe that the search input and button are aligned next to each other with distinct borders and the same width.
3. See error: The search input and button appear disjointed and the input is not wider than the button as expected.

## Expectation
I expected the search input to be wider than the search button and for both elements to be visually integrated as a single component, with no gaps or distinct borders. This would provide a cleaner and more user-friendly interface on mobile screens.

## Screenshots
![Screenshot (732)](https://github.com/user-attachments/assets/5c6fcc51-d481-403e-829b-af952913fb02)

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment] 2024-10-07 14:12
Hi @Demi-la and thankyou for this contribution!

This is a duplicate of #235 Please verify an Issue doesn't already exist before creating a new one.

Please see the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/)

Closing as duplicate.

**Closed by possumbilities** 2024-10-07 14:12 UTC
Labels: 🟧 priority: high, 🚦 status: awaiting triage, 🛠 goal: fix, 💻 aspect: code
